import sqlite3
import os

DB_PATH = os.environ.get("DB_PATH", "saathi.db")


def get_connection() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def init_db() -> None:
    """Create all tables and indexes. Safe to call on every startup."""
    with get_connection() as conn:
        _create_tables(conn)
        _migrate_users_table(conn)
        _create_indexes(conn)
        conn.commit()


# ---------------------------------------------------------------------------
# Table definitions
# ---------------------------------------------------------------------------

def _create_tables(conn: sqlite3.Connection) -> None:

    # ------------------------------------------------------------------
    # users — senior profile. Expanded for full product + v2 dashboard.
    # ------------------------------------------------------------------
    conn.execute("""
        CREATE TABLE IF NOT EXISTS users (
            user_id                 INTEGER PRIMARY KEY,
            name                    TEXT,
            preferred_salutation    TEXT,
            age                     INTEGER,
            city                    TEXT,
            language                TEXT    DEFAULT 'hindi',
            persona                 TEXT    DEFAULT 'friend',
            bot_name                TEXT    DEFAULT 'Saathi',
            formality_level         TEXT    DEFAULT 'warm',
            spouse_name             TEXT,
            religion                TEXT,
            favourite_topics        TEXT,
            music_preferences       TEXT,
            news_interests          TEXT,
            health_sensitivities    TEXT,
            wake_time               TEXT,
            sleep_time              TEXT,
            evening_checkin_time    TEXT,
            heartbeat_consent       INTEGER DEFAULT 0,
            heartbeat_enabled       INTEGER DEFAULT 0,
            onboarding_complete     INTEGER DEFAULT 0,
            onboarding_step         INTEGER DEFAULT 0,
            last_active_at          TEXT,
            created_at              TEXT    DEFAULT (datetime('now')),
            updated_at              TEXT    DEFAULT (datetime('now'))
        )
    """)

    # ------------------------------------------------------------------
    # family_members — linked family with roles + notification prefs.
    # Supports v2 caregiver dashboard access control.
    # ------------------------------------------------------------------
    conn.execute("""
        CREATE TABLE IF NOT EXISTS family_members (
            id                  INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id             INTEGER NOT NULL REFERENCES users(user_id),
            name                TEXT    NOT NULL,
            relationship        TEXT,
            telegram_user_id    INTEGER,
            phone               TEXT,
            role                TEXT    DEFAULT 'family',
            notification_prefs  TEXT    DEFAULT '{}',
            is_setup_user       INTEGER DEFAULT 0,
            created_at          TEXT    DEFAULT (datetime('now'))
        )
    """)

    # ------------------------------------------------------------------
    # messages — full conversation history, in and out.
    # Powers context retrieval and nightly diary summarisation.
    # ------------------------------------------------------------------
    conn.execute("""
        CREATE TABLE IF NOT EXISTS messages (
            id                  INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id             INTEGER NOT NULL REFERENCES users(user_id),
            direction           TEXT    NOT NULL CHECK(direction IN ('in', 'out')),
            message_type        TEXT    NOT NULL DEFAULT 'text',
            content             TEXT,
            telegram_message_id INTEGER,
            voice_file_id       TEXT,
            session_id          TEXT,
            created_at          TEXT    DEFAULT (datetime('now'))
        )
    """)

    # ------------------------------------------------------------------
    # diary_entries — nightly summaries generated by DeepSeek.
    # Primary data source for v2 family dashboard mood trends.
    # ------------------------------------------------------------------
    conn.execute("""
        CREATE TABLE IF NOT EXISTS diary_entries (
            id                      INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id                 INTEGER NOT NULL REFERENCES users(user_id),
            entry_date              TEXT    NOT NULL,
            mood_score              INTEGER CHECK(mood_score BETWEEN 1 AND 5),
            mood_label              TEXT,
            health_complaints       TEXT    DEFAULT '[]',
            family_mentioned        TEXT    DEFAULT '[]',
            songs_requested         TEXT    DEFAULT '[]',
            reminders_acknowledged  INTEGER DEFAULT 0,
            protocol1_triggered     INTEGER DEFAULT 0,
            protocol3_triggered     INTEGER DEFAULT 0,
            emotions_summary        TEXT,
            full_summary            TEXT,
            created_at              TEXT    DEFAULT (datetime('now')),
            UNIQUE(user_id, entry_date)
        )
    """)

    # ------------------------------------------------------------------
    # health_logs — medicine acknowledgements + passive health mentions.
    # Powers medication adherence rate in v2 weekly family report.
    # ------------------------------------------------------------------
    conn.execute("""
        CREATE TABLE IF NOT EXISTS health_logs (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id         INTEGER NOT NULL REFERENCES users(user_id),
            log_type        TEXT    NOT NULL DEFAULT 'mention',
            content         TEXT,
            source          TEXT    DEFAULT 'conversation',
            medicine_name   TEXT,
            reminder_id     INTEGER REFERENCES medicine_reminders(id),
            created_at      TEXT    DEFAULT (datetime('now'))
        )
    """)

    # ------------------------------------------------------------------
    # medicine_reminders — scheduled per user, per medicine.
    # Tracks ack/miss streaks for family adherence report.
    # ------------------------------------------------------------------
    conn.execute("""
        CREATE TABLE IF NOT EXISTS medicine_reminders (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id         INTEGER NOT NULL REFERENCES users(user_id),
            medicine_name   TEXT    NOT NULL,
            dosage          TEXT,
            schedule_time   TEXT    NOT NULL,
            days_of_week    TEXT    DEFAULT 'daily',
            is_active       INTEGER DEFAULT 1,
            last_sent_at    TEXT,
            last_acked_at   TEXT,
            ack_streak      INTEGER DEFAULT 0,
            miss_streak     INTEGER DEFAULT 0,
            created_at      TEXT    DEFAULT (datetime('now'))
        )
    """)

    # ------------------------------------------------------------------
    # memories — life story responses to memory bank questions.
    # Builds personal memoir over months; surfaced in daily rituals.
    # ------------------------------------------------------------------
    conn.execute("""
        CREATE TABLE IF NOT EXISTS memories (
            id                  INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id             INTEGER NOT NULL REFERENCES users(user_id),
            question_id         INTEGER,
            question_text       TEXT,
            response_text       TEXT,
            response_voice_file_id TEXT,
            theme               TEXT,
            created_at          TEXT    DEFAULT (datetime('now'))
        )
    """)

    # ------------------------------------------------------------------
    # heartbeat_log — ping and response history + family alert history.
    # v2 dashboard: last active time, alert frequency.
    # ------------------------------------------------------------------
    conn.execute("""
        CREATE TABLE IF NOT EXISTS heartbeat_log (
            id                  INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id             INTEGER NOT NULL REFERENCES users(user_id),
            ping_time           TEXT    NOT NULL,
            response_time       TEXT,
            ping_number         INTEGER DEFAULT 1,
            family_alerted      INTEGER DEFAULT 0,
            family_alert_time   TEXT,
            alert_type          TEXT,
            created_at          TEXT    DEFAULT (datetime('now'))
        )
    """)

    # ------------------------------------------------------------------
    # protocol_log — Protocol 1 (crisis) and Protocol 3 (financial)
    # trigger events. Anonymised. v2 dashboard: alert history.
    # ------------------------------------------------------------------
    conn.execute("""
        CREATE TABLE IF NOT EXISTS protocol_log (
            id                  INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id             INTEGER NOT NULL REFERENCES users(user_id),
            protocol_type       TEXT    NOT NULL CHECK(protocol_type IN ('1', '3')),
            trigger_bucket      TEXT,
            trigger_keywords    TEXT,
            family_alerted      INTEGER DEFAULT 0,
            family_alert_time   TEXT,
            created_at          TEXT    DEFAULT (datetime('now'))
        )
    """)

    # ------------------------------------------------------------------
    # session_log — session length, frequency, time of day.
    # Over-reliance monitoring: 3am patterns, session frequency.
    # ------------------------------------------------------------------
    conn.execute("""
        CREATE TABLE IF NOT EXISTS session_log (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id         INTEGER NOT NULL REFERENCES users(user_id),
            session_id      TEXT    UNIQUE NOT NULL,
            start_time      TEXT    NOT NULL,
            end_time        TEXT,
            duration_seconds INTEGER,
            message_count   INTEGER DEFAULT 0,
            hour_of_day     INTEGER CHECK(hour_of_day BETWEEN 0 AND 23),
            topics          TEXT    DEFAULT '[]',
            created_at      TEXT    DEFAULT (datetime('now'))
        )
    """)


# ---------------------------------------------------------------------------
# Migration — add new columns to the existing users table without data loss.
# Each ALTER TABLE is attempted individually; if the column already exists
# SQLite raises an OperationalError which we silently ignore.
# ---------------------------------------------------------------------------

_USERS_NEW_COLUMNS = [
    "ALTER TABLE users ADD COLUMN preferred_salutation TEXT",
    "ALTER TABLE users ADD COLUMN city TEXT",
    "ALTER TABLE users ADD COLUMN persona TEXT DEFAULT 'friend'",
    "ALTER TABLE users ADD COLUMN bot_name TEXT DEFAULT 'Saathi'",
    "ALTER TABLE users ADD COLUMN formality_level TEXT DEFAULT 'warm'",
    "ALTER TABLE users ADD COLUMN spouse_name TEXT",
    "ALTER TABLE users ADD COLUMN religion TEXT",
    "ALTER TABLE users ADD COLUMN favourite_topics TEXT",
    "ALTER TABLE users ADD COLUMN music_preferences TEXT",
    "ALTER TABLE users ADD COLUMN news_interests TEXT",
    "ALTER TABLE users ADD COLUMN health_sensitivities TEXT",
    "ALTER TABLE users ADD COLUMN wake_time TEXT",
    "ALTER TABLE users ADD COLUMN sleep_time TEXT",
    "ALTER TABLE users ADD COLUMN evening_checkin_time TEXT",
    "ALTER TABLE users ADD COLUMN heartbeat_consent INTEGER DEFAULT 0",
    "ALTER TABLE users ADD COLUMN heartbeat_enabled INTEGER DEFAULT 0",
    "ALTER TABLE users ADD COLUMN onboarding_step INTEGER DEFAULT 0",
    "ALTER TABLE users ADD COLUMN last_active_at TEXT",
    "ALTER TABLE users ADD COLUMN updated_at TEXT DEFAULT (datetime('now'))",
]


def _migrate_users_table(conn: sqlite3.Connection) -> None:
    for sql in _USERS_NEW_COLUMNS:
        try:
            conn.execute(sql)
        except sqlite3.OperationalError:
            pass  # column already exists


# ---------------------------------------------------------------------------
# Indexes — one per user_id foreign key, plus targeted query helpers.
# ---------------------------------------------------------------------------

def _create_indexes(conn: sqlite3.Connection) -> None:
    indexes = [
        "CREATE INDEX IF NOT EXISTS idx_family_members_user_id    ON family_members(user_id)",
        "CREATE INDEX IF NOT EXISTS idx_messages_user_id           ON messages(user_id)",
        "CREATE INDEX IF NOT EXISTS idx_messages_session_id        ON messages(session_id)",
        "CREATE INDEX IF NOT EXISTS idx_diary_entries_user_id      ON diary_entries(user_id)",
        "CREATE INDEX IF NOT EXISTS idx_diary_entries_date         ON diary_entries(user_id, entry_date)",
        "CREATE INDEX IF NOT EXISTS idx_health_logs_user_id        ON health_logs(user_id)",
        "CREATE INDEX IF NOT EXISTS idx_medicine_reminders_user_id ON medicine_reminders(user_id)",
        "CREATE INDEX IF NOT EXISTS idx_memories_user_id           ON memories(user_id)",
        "CREATE INDEX IF NOT EXISTS idx_heartbeat_log_user_id      ON heartbeat_log(user_id)",
        "CREATE INDEX IF NOT EXISTS idx_protocol_log_user_id       ON protocol_log(user_id)",
        "CREATE INDEX IF NOT EXISTS idx_session_log_user_id        ON session_log(user_id)",
    ]
    for sql in indexes:
        conn.execute(sql)


# ---------------------------------------------------------------------------
# Helper — used by message handlers in main.py
# ---------------------------------------------------------------------------

def log_protocol_event(
    user_id: int,
    protocol_type: str,
    trigger_bucket: str,
    trigger_keywords: str,
    family_alerted: int = 0,
) -> None:
    """Write a Protocol 1 or Protocol 3 trigger event to protocol_log."""
    with get_connection() as conn:
        conn.execute(
            """
            INSERT INTO protocol_log
                (user_id, protocol_type, trigger_bucket, trigger_keywords, family_alerted)
            VALUES (?, ?, ?, ?, ?)
            """,
            (user_id, protocol_type, trigger_bucket, trigger_keywords, family_alerted),
        )
        conn.commit()


def get_or_create_user(user_id: int) -> sqlite3.Row:
    with get_connection() as conn:
        row = conn.execute(
            "SELECT * FROM users WHERE user_id = ?", (user_id,)
        ).fetchone()
        if row is None:
            conn.execute(
                "INSERT INTO users (user_id) VALUES (?)", (user_id,)
            )
            conn.commit()
            row = conn.execute(
                "SELECT * FROM users WHERE user_id = ?", (user_id,)
            ).fetchone()
        return row
